apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: myapp
type: Opaque
data:
  db-username: ZGJ1c2Vy
  db-password: ZGJwYXNzMTIz
  connection-string: bW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNy9teWFwcA==
